-- Seed: Medicamentos e insumos veterinários (~400 itens)
INSERT INTO product_catalog_global (name, category, subcategory, unit, description, common_brand, species) VALUES

-- ═══════════════════════════════════════════════════════════
-- ANTIBIÓTICOS
-- ═══════════════════════════════════════════════════════════
('Amoxicilina 50mg comprimido mastigável','medication','antibiotico','un','Antibiótico β-lactâmico. Dose: 10-20mg/kg BID.',NULL,'{dog,cat}'),
('Amoxicilina 500mg cápsula','medication','antibiotico','un','Antibiótico β-lactâmico amplo espectro.',NULL,'{dog}'),
('Amoxicilina 400mg/5ml suspensão oral','medication','antibiotico','fr','Suspensão oral 100ml. Dose: 10-20mg/kg BID.',NULL,'{dog,cat}'),
('Amoxicilina + Ácido Clavulânico 250mg comprimido','medication','antibiotico','un','Combinação com inibidor de β-lactamase. Dose: 12,5-25mg/kg BID.','Clavamox','{dog,cat}'),
('Amoxicilina + Ácido Clavulânico 500mg comprimido','medication','antibiotico','un','Combinação com inibidor de β-lactamase.','Clavamox','{dog}'),
('Amoxicilina + Ácido Clavulânico 62,5mg/ml suspensão','medication','antibiotico','fr','Suspensão oral 50ml para gatos e cães pequenos.','Clavamox','{dog,cat}'),
('Cefalexina 250mg cápsula','medication','antibiotico','un','Cefalosporina 1ª geração. Dose: 15-30mg/kg BID.',NULL,'{dog,cat}'),
('Cefalexina 500mg cápsula','medication','antibiotico','un','Cefalosporina 1ª geração. Dose: 15-30mg/kg BID.',NULL,'{dog}'),
('Cefalexina 50mg/ml suspensão oral','medication','antibiotico','fr','Suspensão oral 100ml.',NULL,'{dog,cat}'),
('Cefovecina sódica 80mg/ml injetável','medication','antibiotico','fr','Cefalosporina ação prolongada 14 dias. Dose: 8mg/kg SC.','Convenia','{dog,cat}'),
('Clindamicina 150mg cápsula','medication','antibiotico','un','Lincosamida. Indicada para infecções anaerôbias e dentárias.',NULL,'{dog,cat}'),
('Clindamicina 300mg cápsula','medication','antibiotico','un','Lincosamida dose alta para cães grandes.',NULL,'{dog}'),
('Doxiciclina 50mg cápsula','medication','antibiotico','un','Tetraciclina. Dose: 5-10mg/kg SID ou BID.',NULL,'{dog,cat}'),
('Doxiciclina 100mg cápsula','medication','antibiotico','un','Tetraciclina. Indicada para Ehrlichiose e Anaplasmose.',NULL,'{dog}'),
('Doxiciclina 10mg/ml suspensão oral','medication','antibiotico','fr','Suspensão 50ml. Dose: 5-10mg/kg BID.',NULL,'{dog,cat}'),
('Enrofloxacino 15mg comprimido','medication','antibiotico','un','Fluoroquinolona. Dose: 5-20mg/kg SID.','Baytril','{dog,cat}'),
('Enrofloxacino 50mg comprimido','medication','antibiotico','un','Fluoroquinolona. Dose: 5-20mg/kg SID.','Baytril','{dog}'),
('Enrofloxacino 150mg comprimido','medication','antibiotico','un','Fluoroquinolona dose alta cães médios/grandes.','Baytril','{dog}'),
('Enrofloxacino 2,5% solução injetável','medication','antibiotico','fr','Solução 50ml. Dose: 5mg/kg SID IM/SC.','Baytril','{dog,cat}'),
('Marbofloxacino 25mg comprimido','medication','antibiotico','un','Fluoroquinolona. Dose: 2mg/kg SID.','Marbocyl','{dog,cat}'),
('Marbofloxacino 50mg comprimido','medication','antibiotico','un','Fluoroquinolona.',NULL,'{dog}'),
('Pradofloxacino 15mg comprimido','medication','antibiotico','un','Fluoroquinolona 5ª geração para gatos. Dose: 5mg/kg SID.','Veraflox','{cat}'),
('Pradofloxacino 60mg comprimido','medication','antibiotico','un','Fluoroquinolona 5ª geração para cães.','Veraflox','{dog}'),
('Metronidazol 250mg comprimido','medication','antibiotico','un','Nitroimidazol — anaeróbios e Giardia. Dose: 15-25mg/kg BID.',NULL,'{dog,cat}'),
('Metronidazol 500mg comprimido','medication','antibiotico','un','Nitroimidazol dose alta.',NULL,'{dog}'),
('Metronidazol 4mg/ml suspensão oral','medication','antibiotico','fr','Suspensão 100ml para animais pequenos.',NULL,'{dog,cat}'),
('Ampicilina 500mg pó injetável','medication','antibiotico','un','β-lactâmico injetável. Dose: 10-20mg/kg TID.',NULL,'{dog,cat}'),
('Ampicilina + Sulbactam 1,5g pó injetável','medication','antibiotico','un','Combinação IV/IM para infecções graves.',NULL,'{dog,cat}'),
('Sulfadiazina + Trimetropim 80mg+16mg comprimido','medication','antibiotico','un','Potenciada. Dose: 15mg/kg BID.','Trissulfim','{dog,cat}'),
('Sulfadiazina + Trimetropim 80mg+16mg/5ml suspensão','medication','antibiotico','fr','Suspensão 100ml.',NULL,'{dog,cat}'),
('Penicilina G Benzatina 400.000UI injetável','medication','antibiotico','fr','Penicilina longa ação. Dose: 40.000UI/kg IM.',NULL,'{dog,cat}'),
('Penicilina G Benzatina 1.200.000UI injetável','medication','antibiotico','fr','Penicilina longa ação dose alta.',NULL,'{dog}'),
('Gentamicina 50mg/ml injetável','medication','antibiotico','fr','Aminoglicosídeo. Dose: 5-8mg/kg SID IM/SC.',NULL,'{dog,cat}'),
('Neomicina + Bacitracina pomada tópica','medication','antibiotico','tb','Antibiótico tópico para feridas cutâneas.',NULL,'{dog,cat}'),
('Azitromicina 250mg comprimido','medication','antibiotico','un','Macrolídeo. Dose: 5-10mg/kg SID.',NULL,'{dog,cat}'),
('Tilosina 200mg/ml injetável','medication','antibiotico','fr','Macrolídeo para infecções respiratórias.',NULL,'{dog,cat}'),
('Florfenicol 300mg/ml injetável','medication','antibiotico','fr','Amplo espectro para infecções respiratórias.',NULL,'{dog,cat}'),
('Rifampicina 300mg cápsula','medication','antibiotico','un','Rifamicina para infecções estafilocócicas resistentes.',NULL,'{dog,cat}'),
('Lincomicina 500mg cápsula','medication','antibiotico','un','Lincosamida.',NULL,'{dog,cat}'),
('Clindamicina 25mg/ml solução oral','medication','antibiotico','fr','Solução oral. Dose: 5,5-11mg/kg BID.',NULL,'{dog,cat}'),

-- ═══════════════════════════════════════════════════════════
-- ANTI-INFLAMATÓRIOS NÃO ESTEROIDAIS (AINEs)
-- ═══════════════════════════════════════════════════════════
('Meloxicam 0,5mg/ml solução oral','medication','aine','fr','AINE. Dose: 0,1mg/kg no 1° dia, 0,05mg/kg SID manutenção.','Metacam','{dog,cat}'),
('Meloxicam 1mg/ml solução oral','medication','aine','fr','AINE para cães. Dose: 0,2mg/kg no 1° dia.',NULL,'{dog}'),
('Meloxicam 1,5mg comprimido','medication','aine','un','AINE comprimido.',NULL,'{dog}'),
('Meloxicam 2mg comprimido','medication','aine','un','AINE comprimido.',NULL,'{dog}'),
('Carprofeno 25mg comprimido mastigável','medication','aine','un','AINE COX-2. Dose: 2,2mg/kg BID ou 4,4mg/kg SID.','Rimadyl','{dog}'),
('Carprofeno 50mg comprimido mastigável','medication','aine','un','AINE COX-2.','Rimadyl','{dog}'),
('Carprofeno 100mg comprimido mastigável','medication','aine','un','AINE COX-2 para cães grandes.','Rimadyl','{dog}'),
('Robenacoxibe 6mg comprimido','medication','aine','un','AINE para gatos. Dose: 1mg/kg SID 3 dias.','Onsior','{cat}'),
('Robenacoxibe 40mg comprimido','medication','aine','un','AINE para cães grandes.','Onsior','{dog}'),
('Grapiprant 20mg comprimido','medication','aine','un','Inibidor EP4 — menor nefrotoxicidade. Dose: 2mg/kg SID.','Galliprant','{dog}'),
('Grapiprant 60mg comprimido','medication','aine','un','Inibidor EP4 para cães médios.','Galliprant','{dog}'),
('Grapiprant 100mg comprimido','medication','aine','un','Inibidor EP4 para cães grandes.','Galliprant','{dog}'),
('Mavacoxibe 6mg comprimido','medication','aine','un','AINE longa ação (1 dose/mês). Dose: 2mg/kg SID.','Trocoxil','{dog}'),
('Mavacoxibe 75mg comprimido','medication','aine','un','AINE longa ação.','Trocoxil','{dog}'),
('Ketoprofeno 20mg/ml injetável','medication','aine','fr','AINE injetável. Dose: 1mg/kg BID.',NULL,'{dog,cat}'),
('Dipirona 500mg/ml solução injetável','medication','aine','fr','Analgésico/antitérmico. Dose: 25mg/kg TID.',NULL,'{dog,cat}'),
('Dipirona 50mg/ml solução oral','medication','aine','fr','Analgésico/antitérmico oral.',NULL,'{dog,cat}'),
('Firocoxibe 57mg comprimido mastigável','medication','aine','un','AINE COX-2. Dose: 5mg/kg SID.','Previcox','{dog}'),
('Firocoxibe 227mg comprimido mastigável','medication','aine','un','AINE COX-2 para cães grandes.','Previcox','{dog}'),

-- ═══════════════════════════════════════════════════════════
-- CORTICÓIDES
-- ═══════════════════════════════════════════════════════════
('Prednisolona 5mg comprimido','medication','corticoide','un','Corticóide oral. Dose imunossupressora: 2-4mg/kg SID.',NULL,'{dog,cat}'),
('Prednisolona 20mg comprimido','medication','corticoide','un','Corticóide oral dose alta.',NULL,'{dog}'),
('Prednisolona 1mg/ml solução oral','medication','corticoide','fr','Solução oral 100ml.',NULL,'{dog,cat}'),
('Prednisona 5mg comprimido','medication','corticoide','un','Pró-droga da prednisolona.',NULL,'{dog,cat}'),
('Prednisona 20mg comprimido','medication','corticoide','un','Dose anti-inflamatória: 0,5-1mg/kg SID.',NULL,'{dog}'),
('Dexametasona 0,2mg/ml solução injetável','medication','corticoide','fr','Corticóide potente. Dose: 0,1-0,25mg/kg.',NULL,'{dog,cat}'),
('Dexametasona 4mg/ml solução injetável','medication','corticoide','fr','Dexametasona concentrada para emergências.',NULL,'{dog,cat}'),
('Betametasona + Gentamicina spray','medication','corticoide','fr','Spray tópico anti-inflamatório + antibiótico.','Gentalerg','{dog,cat}'),
('Metilprednisolona 20mg/ml injetável','medication','corticoide','fr','Corticóide injetável. Dose: 1-2mg/kg.',NULL,'{dog,cat}'),
('Triancinolona acetonida 10mg/ml injetável','medication','corticoide','fr','Depósito de longa ação. Dose: 0,1-0,2mg/kg IM.',NULL,'{dog,cat}'),
('Acetato de metilprednisolona 40mg/ml injetável','medication','corticoide','fr','Corticóide depósito.','Depo-Medrol','{dog,cat}'),
('Fluticasona 50mcg spray nasal','medication','corticoide','fr','Corticóide intranasal.',NULL,'{dog,cat}'),
('Budesonida 200mcg cápsula inalatória','medication','corticoide','un','Corticóide inalatório para asma felina.',NULL,'{cat}'),

-- ═══════════════════════════════════════════════════════════
-- ANTIPARASITÁRIOS EXTERNOS (ECTOPARASITICIDAS)
-- ═══════════════════════════════════════════════════════════
('Afoxolaner 11,3mg mastigável','medication','ectoparasiticida','un','Isoxazolina. Cães até 2,5kg. Pulgas e carrapatos.','NexGard','{dog}'),
('Afoxolaner 28,3mg mastigável','medication','ectoparasiticida','un','Cães 2,5-10kg.','NexGard','{dog}'),
('Afoxolaner 68mg mastigável','medication','ectoparasiticida','un','Cães 10-25kg.','NexGard','{dog}'),
('Afoxolaner 136mg mastigável','medication','ectoparasiticida','un','Cães 25-50kg.','NexGard','{dog}'),
('Fluralaner 112,5mg mastigável','medication','ectoparasiticida','un','Isoxazolina. Cães até 4,5kg. 12 semanas.','Bravecto','{dog}'),
('Fluralaner 250mg mastigável','medication','ectoparasiticida','un','Cães 4,5-10kg. 12 semanas.','Bravecto','{dog}'),
('Fluralaner 500mg mastigável','medication','ectoparasiticida','un','Cães 10-20kg. 12 semanas.','Bravecto','{dog}'),
('Fluralaner 1000mg mastigável','medication','ectoparasiticida','un','Cães 20-40kg. 12 semanas.','Bravecto','{dog}'),
('Fluralaner spot-on gatos 112,5mg','medication','ectoparasiticida','un','Bravecto spot-on para gatos até 12,5kg.','Bravecto','{cat}'),
('Sarolaner 5mg mastigável','medication','ectoparasiticida','un','Isoxazolina mensal. Cães 1,3-2,5kg.','Simparica','{dog}'),
('Sarolaner 10mg mastigável','medication','ectoparasiticida','un','Cães 2,5-5kg.','Simparica','{dog}'),
('Sarolaner 20mg mastigável','medication','ectoparasiticida','un','Cães 5-10kg.','Simparica','{dog}'),
('Sarolaner 40mg mastigável','medication','ectoparasiticida','un','Cães 10-20kg.','Simparica','{dog}'),
('Sarolaner 80mg mastigável','medication','ectoparasiticida','un','Cães 20-40kg.','Simparica','{dog}'),
('Lotilaner 56,25mg mastigável','medication','ectoparasiticida','un','Isoxazolina mensal. Cães 1,3-2,5kg.','Credelio','{dog}'),
('Lotilaner 112,5mg mastigável','medication','ectoparasiticida','un','Cães 2,5-5,5kg.','Credelio','{dog}'),
('Lotilaner 225mg mastigável','medication','ectoparasiticida','un','Cães 5,5-11kg.','Credelio','{dog}'),
('Lotilaner 450mg mastigável','medication','ectoparasiticida','un','Cães 11-22kg.','Credelio','{dog}'),
('Lotilaner 900mg mastigável','medication','ectoparasiticida','un','Cães 22-45kg.','Credelio','{dog}'),
('Selamectina 6% spot-on 15mg','medication','ectoparasiticida','un','Avermectina. Gatos e cães ≤2,5kg.','Revolution','{dog,cat}'),
('Selamectina 6% spot-on 30mg','medication','ectoparasiticida','un','Cães 2,6-5kg.','Revolution','{dog}'),
('Selamectina 6% spot-on 60mg','medication','ectoparasiticida','un','Cães 5,1-10kg.','Revolution','{dog}'),
('Selamectina 6% spot-on 120mg','medication','ectoparasiticida','un','Cães 10,1-20kg.','Revolution','{dog}'),
('Selamectina 6% spot-on 240mg','medication','ectoparasiticida','un','Cães 20,1-40kg.','Revolution','{dog}'),
('Imidacloprida + Permetrina 10% spot-on','medication','ectoparasiticida','un','Pulgas e carrapatos. Cães. Não usar em gatos.','Advantix','{dog}'),
('Imidacloprida + Flumetrina collar','medication','ectoparasiticida','un','Coleira 8 meses cães. Não usar em gatos.','Seresto','{dog}'),
('Imidacloprida + Flumetrina collar gatos','medication','ectoparasiticida','un','Coleira 8 meses gatos.','Seresto','{cat}'),
('Spinosad 140mg mastigável','medication','ectoparasiticida','un','Espinossídeo. Cães 2-3,9kg.','Comfortis','{dog}'),
('Spinosad 270mg mastigável','medication','ectoparasiticida','un','Cães 4-7,9kg.','Comfortis','{dog}'),
('Spinosad 560mg mastigável','medication','ectoparasiticida','un','Cães 8-13,9kg.','Comfortis','{dog}'),
('Spinosad 810mg mastigável','medication','ectoparasiticida','un','Cães 14-27kg.','Comfortis','{dog}'),
('Spinosad 1620mg mastigável','medication','ectoparasiticida','un','Cães 27-54kg.','Comfortis','{dog}'),
('Nitenpyram 11,4mg comprimido','medication','ectoparasiticida','un','Ação imediata antipulgas. Cães ≤11kg.','Capstar','{dog,cat}'),
('Nitenpyram 57mg comprimido','medication','ectoparasiticida','un','Ação imediata antipulgas. Cães >11kg.','Capstar','{dog}'),
('Ivermectina 1% solução injetável','medication','ectoparasiticida','fr','Avermectina. Dose: 0,2-0,4mg/kg SC.',NULL,'{dog}'),
('Ivermectina 3mg comprimido','medication','ectoparasiticida','un','Antipulgas/carrapatos oral.',NULL,'{dog}'),
('Permetrina 65% spot-on','medication','ectoparasiticida','un','Piretroide tópico. APENAS CÃES.',NULL,'{dog}'),
('Fipronil 0,25% spray','medication','ectoparasiticida','fr','Fenilpirazol. 100ml. Pulgas e carrapatos.','Frontline','{dog,cat}'),
('Fipronil + S-Metopreno spot-on pequeno','medication','ectoparasiticida','un','Pulgas + ovos. Cães até 10kg.','Frontline Plus','{dog}'),
('Fipronil + S-Metopreno spot-on médio','medication','ectoparasiticida','un','Cães 10-20kg.','Frontline Plus','{dog}'),
('Fipronil + S-Metopreno spot-on grande','medication','ectoparasiticida','un','Cães 20-40kg.','Frontline Plus','{dog}'),
('Fipronil + S-Metopreno spot-on gatos','medication','ectoparasiticida','un','Para gatos.','Frontline Plus','{cat}'),

-- ═══════════════════════════════════════════════════════════
-- ANTIPARASITÁRIOS INTERNOS (ENDOPARASITICIDAS)
-- ═══════════════════════════════════════════════════════════
('Praziquantel 50mg comprimido','medication','endoparasiticida','un','Teniacida/cestodicida. Dose: 5mg/kg.',NULL,'{dog,cat}'),
('Praziquantel 150mg comprimido','medication','endoparasiticida','un','Dose única para tênias.',NULL,'{dog}'),
('Febendazol 150mg comprimido','medication','endoparasiticida','un','Benzimidazol. Dose: 50mg/kg SID 3 dias.',NULL,'{dog,cat}'),
('Febendazol 500mg comprimido','medication','endoparasiticida','un','Dose alta para cães médios/grandes.',NULL,'{dog}'),
('Febendazol 100mg/ml suspensão oral','medication','endoparasiticida','fr','Suspensão para uso em filhotes.',NULL,'{dog,cat}'),
('Albendazol 100mg/ml suspensão oral','medication','endoparasiticida','fr','Dose: 25-50mg/kg SID 3 dias.',NULL,'{dog}'),
('Mebendazol 100mg comprimido','medication','endoparasiticida','un','Benzimidazol amplo espectro.',NULL,'{dog,cat}'),
('Pirantel 500mg comprimido','medication','endoparasiticida','un','Nematodicida. Dose: 5-10mg/kg.',NULL,'{dog,cat}'),
('Febantel + Praziquantel + Pirantel comprimido cão P','medication','endoparasiticida','un','Vermífugo amplo espectro. Cães até 3kg.','Drontal Plus','{dog}'),
('Febantel + Praziquantel + Pirantel comprimido cão M','medication','endoparasiticida','un','Cães 3-10kg.','Drontal Plus','{dog}'),
('Febantel + Praziquantel + Pirantel comprimido cão G','medication','endoparasiticida','un','Cães 10-35kg.','Drontal Plus','{dog}'),
('Praziquantel + Pirantel comprimido gato','medication','endoparasiticida','un','Vermífugo para gatos.','Drontal Gatos','{cat}'),
('Milbemicina oxima + Praziquantel 2,3mg+25,6mg','medication','endoparasiticida','un','Vermífugo + prevenção de verme do coração. Cães até 1kg.','Milbemax','{dog}'),
('Milbemicina oxima + Praziquantel 12,5mg+125mg','medication','endoparasiticida','un','Cães 5-25kg.','Milbemax','{dog}'),
('Emodepside + Praziquantel spot-on gatos','medication','endoparasiticida','un','Vermífugo spot-on gatos.','Profender','{cat}'),
('Nitazoxanida 200mg comprimido','medication','endoparasiticida','un','Criptosporidiose e Giardia.',NULL,'{dog,cat}'),
('Metronidazol 250mg comprimido (Giardia)','medication','endoparasiticida','un','Giardiacida. Dose: 25mg/kg BID 5-7 dias.',NULL,'{dog,cat}'),

-- ═══════════════════════════════════════════════════════════
-- ANTIFÚNGICOS
-- ═══════════════════════════════════════════════════════════
('Cetoconazol 200mg comprimido','medication','antifungico','un','Azol sistêmico. Dose: 5-10mg/kg SID.',NULL,'{dog,cat}'),
('Cetoconazol 2% shampoo terapêutico','medication','antifungico','fr','Shampoo 125ml para dermatites fúngicas.',NULL,'{dog,cat}'),
('Cetoconazol 2% creme tópico','medication','antifungico','tb','Creme 30g para lesões cutâneas.',NULL,'{dog,cat}'),
('Itraconazol 50mg cápsula','medication','antifungico','un','Azol para Sporothrix e dermatofitose.','Itrafar','{cat}'),
('Itraconazol 100mg cápsula','medication','antifungico','un','Dose: 5-10mg/kg SID.',NULL,'{dog}'),
('Fluconazol 50mg cápsula','medication','antifungico','un','Triazol. Dose: 5-10mg/kg SID.',NULL,'{dog,cat}'),
('Fluconazol 150mg cápsula','medication','antifungico','un','Dose semana única para candidíase.',NULL,'{dog}'),
('Terbinafina 250mg comprimido','medication','antifungico','un','Para dermatofitose. Dose: 30-40mg/kg SID.',NULL,'{dog,cat}'),
('Nistatina suspensão oral','medication','antifungico','fr','Candidíase oral/intestinal. Não absorvida.',NULL,'{dog,cat}'),
('Clotrimazol 1% solução otológica','medication','antifungico','fr','Para otites fúngicas. Aplicar 2x ao dia.',NULL,'{dog,cat}'),
('Miconazol 2% creme tópico','medication','antifungico','tb','Imidazol tópico para lesões cutâneas.',NULL,'{dog,cat}'),
('Anfotericina B lipossomal 50mg injetável','medication','antifungico','fr','Para micoses sistêmicas graves.',NULL,'{dog,cat}'),
('Voriconazol 50mg comprimido','medication','antifungico','un','Triazol 2ª geração para Aspergillus.',NULL,'{dog,cat}'),
('Griseofulvina 500mg comprimido','medication','antifungico','un','Para dermatofitose em gatos jovens.',NULL,'{cat}'),

-- ═══════════════════════════════════════════════════════════
-- CARDIOLÓGICOS
-- ═══════════════════════════════════════════════════════════
('Enalapril 2,5mg comprimido','medication','cardiologico','un','IECA. Dose: 0,5mg/kg BID.',NULL,'{dog,cat}'),
('Enalapril 5mg comprimido','medication','cardiologico','un','IECA.',NULL,'{dog}'),
('Enalapril 10mg comprimido','medication','cardiologico','un','IECA dose alta.',NULL,'{dog}'),
('Benazepril 2,5mg comprimido','medication','cardiologico','un','IECA. Dose: 0,25-0,5mg/kg SID.','Fortekor','{dog,cat}'),
('Benazepril 5mg comprimido','medication','cardiologico','un','IECA.','Fortekor','{dog,cat}'),
('Benazepril 20mg comprimido','medication','cardiologico','un','IECA dose alta.','Fortekor','{dog}'),
('Furosemida 10mg comprimido','medication','cardiologico','un','Diurético de alça. Dose: 1-4mg/kg BID.',NULL,'{dog,cat}'),
('Furosemida 40mg comprimido','medication','cardiologico','un','Dose para insuficiência cardíaca.',NULL,'{dog}'),
('Furosemida 5mg/ml solução injetável','medication','cardiologico','fr','Dose de emergência em edema pulmonar.',NULL,'{dog,cat}'),
('Espironolactona 25mg comprimido','medication','cardiologico','un','Diurético poupador de potássio.',NULL,'{dog,cat}'),
('Espironolactona 50mg comprimido','medication','cardiologico','un','Aldosterona antagonista.',NULL,'{dog}'),
('Atenolol 25mg comprimido','medication','cardiologico','un','Beta-bloqueador. Dose: 0,5-2mg/kg BID.',NULL,'{dog,cat}'),
('Atenolol 50mg comprimido','medication','cardiologico','un','Beta-bloqueador.',NULL,'{dog}'),
('Amlodipina 2,5mg comprimido','medication','cardiologico','un','Bloqueador canal de cálcio. Dose gato: 0,625-1,25mg SID.','Norvasc','{dog,cat}'),
('Amlodipina 5mg comprimido','medication','cardiologico','un','Dose cão e controle pressórico felino.',NULL,'{dog}'),
('Digoxina 0,0625mg comprimido','medication','cardiologico','un','Glicosídeo cardíaco. Dose gatos.',NULL,'{cat}'),
('Digoxina 0,25mg comprimido','medication','cardiologico','un','Glicosídeo cardíaco para cães.',NULL,'{dog}'),
('Pimobendan 1,25mg mastigável','medication','cardiologico','un','Inodilatador. Dose: 0,25mg/kg BID.','Vetmedin','{dog}'),
('Pimobendan 2,5mg mastigável','medication','cardiologico','un','Insuficiência cardíaca congestiva.','Vetmedin','{dog}'),
('Pimobendan 5mg mastigável','medication','cardiologico','un','Dose alta para cães grandes.','Vetmedin','{dog}'),
('Diltiazem 30mg comprimido','medication','cardiologico','un','Bloqueador canal de cálcio. Taquiarritmias.',NULL,'{dog,cat}'),
('Sotalol 80mg comprimido','medication','cardiologico','un','Antiarrítmico. Fibrilação ventricular.',NULL,'{dog}'),
('Hidralazina 25mg comprimido','medication','cardiologico','un','Vasodilatador arterial.',NULL,'{dog}'),
('Sildenafil 25mg comprimido','medication','cardiologico','un','Inibidor PDE5. Hipertensão pulmonar.',NULL,'{dog,cat}'),
('Telmisartana 40mg comprimido','medication','cardiologico','un','BRA. Proteção renal felina.','Semintra','{cat}'),

-- ═══════════════════════════════════════════════════════════
-- GASTROINTESTINAIS
-- ═══════════════════════════════════════════════════════════
('Omeprazol 20mg cápsula','medication','gastrointestinal','un','IBP. Dose: 0,5-1mg/kg SID.',NULL,'{dog,cat}'),
('Omeprazol 40mg/5ml pó injetável','medication','gastrointestinal','fr','Uso hospitalar IV.',NULL,'{dog,cat}'),
('Pantoprazol 20mg comprimido','medication','gastrointestinal','un','IBP alternativo.',NULL,'{dog,cat}'),
('Famotidina 10mg comprimido','medication','gastrointestinal','un','Anti-H2. Dose: 0,5mg/kg BID.',NULL,'{dog,cat}'),
('Famotidina 0,2mg/ml solução injetável','medication','gastrointestinal','fr','Uso hospitalar.',NULL,'{dog,cat}'),
('Sucralfato 1g sachê','medication','gastrointestinal','un','Protetor mucosa gástrica.',NULL,'{dog,cat}'),
('Sucralfato 200mg/ml suspensão oral','medication','gastrointestinal','fr','Suspensão 100ml para úlceras.',NULL,'{dog,cat}'),
('Metoclopramida 5mg comprimido','medication','gastrointestinal','un','Procinético/antiemético. Dose: 0,2-0,5mg/kg TID.',NULL,'{dog,cat}'),
('Metoclopramida 0,5mg/ml solução injetável','medication','gastrointestinal','fr','Antiemético injetável.',NULL,'{dog,cat}'),
('Ondansetrona 4mg comprimido','medication','gastrointestinal','un','Antiemético serotonérgico. Dose: 0,1-0,2mg/kg BID.',NULL,'{dog,cat}'),
('Ondansetrona 2mg/ml solução injetável','medication','gastrointestinal','fr','Antiemético IV.',NULL,'{dog,cat}'),
('Maropitant 16mg comprimido','medication','gastrointestinal','un','NK1. Dose: 2mg/kg SID. Gatos.','Cerenia','{cat}'),
('Maropitant 24mg comprimido','medication','gastrointestinal','un','Dose para cães pequenos.','Cerenia','{dog}'),
('Maropitant 60mg comprimido','medication','gastrointestinal','un','Cães médios/grandes.','Cerenia','{dog}'),
('Maropitant 10mg/ml solução injetável','medication','gastrointestinal','fr','Antiemético de 1ª linha. Dose: 1mg/kg SC SID.','Cerenia','{dog,cat}'),
('Domperidona 1mg/ml suspensão oral','medication','gastrointestinal','fr','Procinético. Dose: 0,1-0,3mg/kg TID.',NULL,'{dog,cat}'),
('Loperamida 2mg cápsula','medication','gastrointestinal','un','Antidiarreico. Dose: 0,08-0,16mg/kg TID.',NULL,'{dog}'),
('Misoprostol 200mcg comprimido','medication','gastrointestinal','un','Protetor gástrico (AINE-induced gastropathy).',NULL,'{dog,cat}'),
('Carvão ativado 250g pó oral','medication','gastrointestinal','un','Adsorvente em intoxicações. Dose: 1-4g/kg.',NULL,'{dog,cat}'),
('Bismuto subsalicilato suspensão','medication','gastrointestinal','fr','Antidiarreico. Dose: 1ml/kg TID.',NULL,'{dog}'),
('Lactulose 3,33g/5ml xarope','medication','gastrointestinal','fr','Laxante/encefalopatia hepática.',NULL,'{dog,cat}'),
('Psyllium 3,5g sachê fibra solúvel','medication','gastrointestinal','un','Suplemento de fibra. Prisão de ventre.',NULL,'{dog,cat}'),

-- ═══════════════════════════════════════════════════════════
-- NEUROLÓGICOS / COMPORTAMENTAIS
-- ═══════════════════════════════════════════════════════════
('Fenobarbital 40mg comprimido','controlled_medication','neurologico','un','Anticonvulsivante. Dose: 2-4mg/kg BID. Controlado.',NULL,'{dog,cat}'),
('Fenobarbital 100mg comprimido','controlled_medication','neurologico','un','Dose para cães maiores. Controlado.',NULL,'{dog}'),
('Fenobarbital 65mg/ml solução oral','controlled_medication','neurologico','fr','Solução oral 100ml. Controlado.',NULL,'{dog,cat}'),
('Brometo de potássio 325mg cápsula','medication','neurologico','un','Anticonvulsivante adjuvante.',NULL,'{dog}'),
('Imepitoin 100mg comprimido','medication','neurologico','un','Anticonvulsivante. Efeitos menores.','Pexion','{dog}'),
('Imepitoin 400mg comprimido','medication','neurologico','un','Dose plena para epilepsia.','Pexion','{dog}'),
('Levetiracetam 250mg comprimido','medication','neurologico','un','Anticonvulsivante adjuvante. Dose: 20mg/kg TID.',NULL,'{dog,cat}'),
('Diazepam 5mg comprimido','controlled_medication','neurologico','un','Benzodiazepínico. Dose aguda: 0,5-1mg/kg. Controlado.',NULL,'{dog,cat}'),
('Diazepam 5mg/ml solução injetável','controlled_medication','neurologico','fr','Status epilepticus IV/IM. Controlado.',NULL,'{dog,cat}'),
('Midazolam 5mg/ml solução injetável','controlled_medication','neurologico','fr','Benzodiazepínico injetável. Controlado.',NULL,'{dog,cat}'),
('Gabapentina 100mg cápsula','medication','neurologico','un','Anticonvulsivante e analgésico. Dose: 5-10mg/kg BID.',NULL,'{dog,cat}'),
('Gabapentina 300mg cápsula','medication','neurologico','un','Dose neuropatia.',NULL,'{dog}'),
('Pregabalina 75mg cápsula','medication','neurologico','un','Análogo GABA. Dor neuropática.',NULL,'{dog}'),
('Fluoxetina 10mg cápsula','medication','comportamental','un','ISRS. Ansiedade/TOC. Dose: 1mg/kg SID.',NULL,'{dog,cat}'),
('Fluoxetina 20mg cápsula','medication','comportamental','un','Dose cão médio/grande.',NULL,'{dog}'),
('Clomipramina 5mg comprimido','medication','comportamental','un','Tricíclico. Ansiedade separação. Dose: 1-3mg/kg BID.','Clomicalm','{dog}'),
('Clomipramina 20mg comprimido','medication','comportamental','un','Dose plena. Cão médio/grande.','Clomicalm','{dog}'),
('Selegilina 5mg comprimido','medication','comportamental','un','IMAO-B. Disfunção cognitiva canina.','Selgian','{dog}'),
('Trazodona 50mg comprimido','medication','comportamental','un','Ansiolítico. Dose: 2-5mg/kg SID.',NULL,'{dog,cat}'),
('Alprazolam 0,25mg comprimido','controlled_medication','comportamental','un','Benzodiazepínico. Fobia a ruídos. Controlado.',NULL,'{dog,cat}'),

-- ═══════════════════════════════════════════════════════════
-- ANESTÉSICOS E ANALGÉSICOS
-- ═══════════════════════════════════════════════════════════
('Propofol 10mg/ml emulsão injetável','medication','anestesico','fr','Anestésico IV. Dose indução: 4-6mg/kg IV.',NULL,'{dog,cat}'),
('Cetamina 10% solução injetável','controlled_medication','anestesico','fr','Dissociativo. Dose sedação: 10-20mg/kg IM. Controlado.',NULL,'{dog,cat}'),
('Xilazina 2% solução injetável','medication','anestesico','fr','Alfa-2 agonista. Sedação/MPA. Dose: 1-2mg/kg IM.',NULL,'{dog,cat}'),
('Dexmedetomidina 0,5mg/ml injetável','medication','anestesico','fr','Alfa-2 agonista seletivo. Dose: 5-20mcg/kg IM/IV.','Dexdomitor','{dog,cat}'),
('Medetomidina 1mg/ml injetável','medication','anestesico','fr','Alfa-2 agonista.',NULL,'{dog,cat}'),
('Acepromazina 1% solução injetável','medication','anestesico','fr','Fenotiazínico. MPA. Dose: 0,025-0,1mg/kg IM/SC.',NULL,'{dog,cat}'),
('Tiletamina + Zolazepam 50mg/ml injetável','controlled_medication','anestesico','fr','Anestésico dissociativo. Controlado.','Zoletil','{dog,cat}'),
('Butorfanol 10mg/ml solução injetável','controlled_medication','anestesico','fr','Opioide κ-agonista. Dose: 0,2-0,4mg/kg. Controlado.',NULL,'{dog,cat}'),
('Tramadol 50mg comprimido','controlled_medication','analgesia','un','Opioide fraco. Dose: 2-5mg/kg BID. Controlado.',NULL,'{dog,cat}'),
('Tramadol 100mg/ml solução injetável','controlled_medication','analgesia','fr','Dose pós-operatória. Controlado.',NULL,'{dog,cat}'),
('Morfina 10mg/ml solução injetável','controlled_medication','analgesia','fr','Opioide forte. Dose: 0,1-0,5mg/kg IM. Controlado.',NULL,'{dog,cat}'),
('Metadona 10mg/ml solução injetável','controlled_medication','analgesia','fr','Opioide. Protocolo TIVA. Controlado.',NULL,'{dog,cat}'),
('Buprenorfina 0,3mg/ml solução injetável','controlled_medication','analgesia','fr','Opioide parcial. Dose: 0,01-0,02mg/kg. Controlado.',NULL,'{dog,cat}'),
('Fentanil 50mcg/ml solução injetável','controlled_medication','analgesia','fr','Opioide de curta ação IV. Controlado.',NULL,'{dog,cat}'),
('Bupivacaína 0,5% solução injetável','medication','anestesico','fr','Anestésico local de longa ação. Bloqueios locorregionais.',NULL,'{dog,cat}'),
('Lidocaína 2% injetável sem vasoconstritor','medication','anestesico','fr','Anestésico local. Bloqueio epidural.',NULL,'{dog,cat}'),
('Lidocaína 2% injetável com adrenalina','medication','anestesico','fr','Anestésico local + vasoconstritor. Uso oral/tópico.',NULL,'{dog,cat}'),
('Isoflurano 100ml líquido volátil','medication','anestesico','fr','Agente inalatório. Manutenção anestésica.',NULL,'{dog,cat}'),
('Sevoflurano 250ml líquido volátil','medication','anestesico','fr','Inalatório. Indução + manutenção.',NULL,'{dog,cat}'),
('Propofol 20mg/ml emulsão injetável','medication','anestesico','fr','Concentrado. TIVA contínua.',NULL,'{dog,cat}'),

-- ═══════════════════════════════════════════════════════════
-- OFTÁLMICOS
-- ═══════════════════════════════════════════════════════════
('Tobramicina 0,3% colírio','medication','oftalmico','fr','Antibiótico ocular. 3-5 gotas TID.',NULL,'{dog,cat}'),
('Tobramicina + Dexametasona colírio','medication','oftalmico','fr','Antibiótico + anti-inflamatório ocular.',NULL,'{dog,cat}'),
('Ciprofloxacino 0,3% colírio','medication','oftalmico','fr','Quinolona oftálmica. TID-QID.',NULL,'{dog,cat}'),
('Ofloxacino 0,3% colírio','medication','oftalmico','fr','Quinolona de amplo espectro ocular.',NULL,'{dog,cat}'),
('Cloranfenicol 1% pomada oftálmica','medication','oftalmico','tb','Antibiótico pomada ocular. BID.',NULL,'{dog,cat}'),
('Lágrima artificial carboximetilcelulose colírio','medication','oftalmico','fr','Lubrificante ocular. KCS (olho seco).',NULL,'{dog,cat}'),
('Lágrima artificial gel de carbômero','medication','oftalmico','tb','Gel lubrificante noturno para KCS.',NULL,'{dog,cat}'),
('Ciclosporina 0,2% pomada oftálmica','medication','oftalmico','tb','Imunomodulador. KCS. 1 aplicação BID.','Optimmune','{dog}'),
('Ciclosporina 2% solução oftálmica','medication','oftalmico','fr','KCS felina.',NULL,'{cat}'),
('Tacrolimo 0,02% pomada oftálmica','medication','oftalmico','tb','Imunomodulador para KCS resistente à ciclosporina.',NULL,'{dog,cat}'),
('Timolol 0,5% colírio','medication','oftalmico','fr','Beta-bloqueador. Reduz PIO (glaucoma). BID.',NULL,'{dog,cat}'),
('Latanoprost 0,005% colírio','medication','oftalmico','fr','Prostaglandina. Glaucoma. 1 gota SID.',NULL,'{dog,cat}'),
('Dorzolamida 2% colírio','medication','oftalmico','fr','Inibidor AC. Glaucoma. BID-TID.',NULL,'{dog,cat}'),
('Dorzolamida + Timolol colírio combinado','medication','oftalmico','fr','Dupla ação antiglaucomatosa.',NULL,'{dog,cat}'),
('Atropina 1% colírio','medication','oftalmico','fr','Midriático/cicloplégico. Uveíte.',NULL,'{dog,cat}'),
('Prednisolona acetato 1% colírio','medication','oftalmico','fr','Corticóide ocular para uveíte.',NULL,'{dog,cat}'),
('Dexametasona 0,1% colírio','medication','oftalmico','fr','Anti-inflamatório ocular pós-cirúrgico.',NULL,'{dog,cat}'),
('N-acetilcisteína 10% colírio','medication','oftalmico','fr','Úlceras melting. Colagenase inibidor.',NULL,'{dog,cat}'),
('Hialuronato de sódio 0,2% colírio','medication','oftalmico','fr','Lubrificante ocular de alta viscosidade.',NULL,'{dog,cat}'),
('Neomicina + Polimixina + Hidrocortisona colírio','medication','oftalmico','fr','Antibiótico + corticóide ocular.',NULL,'{dog,cat}'),

-- ═══════════════════════════════════════════════════════════
-- OTOLÓGICOS
-- ═══════════════════════════════════════════════════════════
('Gentamicina + Betametasona + Clotrimazol pomada auricular','medication','otologico','tb','Otite externa mista (bacteriana + fúngica + inflamatória).','Otomax','{dog,cat}'),
('Mometasona + Gentamicina + Clotrimazol pomada auricular','medication','otologico','tb','Otite externa. Apenas 1 aplicação/dia.','Mometamax','{dog,cat}'),
('Polimixina B + Miconazol + Prednisolona gotas auriculares','medication','otologico','fr','Otite externa mista. 5 gotas BID.','Surolan','{dog,cat}'),
('Clorexidina 0,15% limpador auricular','medication','otologico','fr','Limpeza de ouvidos. Uso semanal.',NULL,'{dog,cat}'),
('Ácido bórico + Salicílico limpador auricular','medication','otologico','fr','Antisséptico e secativo para ouvidos.',NULL,'{dog,cat}'),
('Fluocinolona + Dimetilsulfóxido solução auricular','medication','otologico','fr','Anti-inflamatório + penetrador. Otite média.','Synotic','{dog}'),
('Ivermectina 0,01% gotas auriculares','medication','otologico','fr','Ácaros auriculares (Otodectes).','Acarexx','{dog,cat}'),
('Selamectina 6% spot-on (ação auricular)','medication','otologico','un','Ácaros auriculares via spot-on.','Revolution','{dog,cat}'),

-- ═══════════════════════════════════════════════════════════
-- DERMATOLÓGICOS
-- ═══════════════════════════════════════════════════════════
('Oclacitinib 3,6mg comprimido','medication','dermatologico','un','JAK inibidor. Prurido alérgico. Dose: 0,4-0,6mg/kg BID 14d.','Apoquel','{dog}'),
('Oclacitinib 5,4mg comprimido','medication','dermatologico','un','Dose para cães 10-15kg.','Apoquel','{dog}'),
('Oclacitinib 16mg comprimido','medication','dermatologico','un','Dose para cães >30kg.','Apoquel','{dog}'),
('Lokivetmab 10mg injetável','medication','dermatologico','un','Anticorpo anti-IL31. Prurido. SC mensal.','Cytopoint','{dog}'),
('Lokivetmab 20mg injetável','medication','dermatologico','un','Dose para cães 10-20kg.','Cytopoint','{dog}'),
('Lokivetmab 30mg injetável','medication','dermatologico','un','Dose para cães 20-30kg.','Cytopoint','{dog}'),
('Lokivetmab 40mg injetável','medication','dermatologico','un','Dose para cães >30kg.','Cytopoint','{dog}'),
('Clorexidina 4% sabonete dermatológico','medication','dermatologico','fr','Antisséptico. Piodermite superficial.',NULL,'{dog,cat}'),
('Mupirocina 2% pomada','medication','dermatologico','tb','Antibiótico tópico Gram+. Pioderma focal.',NULL,'{dog,cat}'),
('Hidrocortisona 1% creme','medication','dermatologico','tb','Corticóide tópico leve. Prurido localizado.',NULL,'{dog,cat}'),
('Betametasona 0,05% creme','medication','dermatologico','tb','Corticóide tópico potente.',NULL,'{dog,cat}'),
('Tacrolimo 0,1% pomada','medication','dermatologico','tb','Imunomodulador tópico. Dermatite atópica.',NULL,'{dog,cat}'),
('Mupirocina + Polietilenoglicol pomada','medication','dermatologico','tb','Antibiótico tópico para foliculite.',NULL,'{dog}'),
('Peróxido de benzoíla 2,5% shampoo','medication','dermatologico','fr','Queratolítico + antibacteriano.',NULL,'{dog}'),
('Enilconazol 10% solução tópica','medication','dermatologico','fr','Dermatofitose. Diluir 1:50 em água.','Imaverol','{dog,cat}'),
('Lime sulfur 27% solução diluição','medication','dermatologico','fr','Sarnoptes e Demodex generalizado. Diluir 1:16.',NULL,'{dog,cat}'),
('Amitraz 12,5% solução parasiticida','medication','dermatologico','fr','Demodecidida tópica. Diluir para 0,025%.','Triatix','{dog}'),
('Doramectina 1% injetável','medication','dermatologico','fr','Sarna demodécica grave. Dose: 0,4mg/kg SC semanal.',NULL,'{dog}'),
('Fluralaner spot-on 112,5mg (Demodex)','medication','dermatologico','un','Bravecto off-label Demodex.','Bravecto','{dog}'),
('Espironolactona + Cetoconazol + Ácido salicílico shampoo','medication','dermatologico','fr','Seborréia e dermatite seborreica.',NULL,'{dog}'),

-- ═══════════════════════════════════════════════════════════
-- SUPLEMENTOS E VITAMINAS
-- ═══════════════════════════════════════════════════════════
('Ômega 3 óleo de salmão 125ml','medication','suplemento','fr','EFA. Suporte derm, articular e renal.',NULL,'{dog,cat}'),
('Ômega 3 500mg cápsulas','medication','suplemento','un','EPA+DHA. Anti-inflamatório natural.',NULL,'{dog,cat}'),
('Complexo B injetável 20ml','medication','suplemento','fr','Vitaminas B1+B6+B12.',NULL,'{dog,cat}'),
('Vitamina B12 1000mcg/ml injetável','medication','suplemento','fr','Cobalamina. Anemia megaloblástica.',NULL,'{dog,cat}'),
('Vitamina C 200mg/ml injetável','medication','suplemento','fr','Ácido ascórbico. Suporte imune/antioxidante.',NULL,'{dog,cat}'),
('Vitamina K1 10mg/ml injetável','medication','suplemento','fr','Antídoto rodenticidas. Dose: 2,5-5mg/kg SC.',NULL,'{dog,cat}'),
('Biotina 5mg comprimido','medication','suplemento','un','Suporte pelagem e unhas.',NULL,'{dog,cat}'),
('Selênio + Vitamina E injetável','medication','suplemento','fr','Antioxidante. Distrofia muscular.',NULL,'{dog,cat}'),
('Ferro dextrano 100mg/ml injetável','medication','suplemento','fr','Anemia ferropriva. Dose: 10-20mg/kg IM.',NULL,'{dog,cat}'),
('Suplemento articular condroitina + glucosamina','medication','suplemento','un','Condroprotetor. Osteoartrite.',NULL,'{dog,cat}'),
('Suplemento articular MSM 500mg','medication','suplemento','un','Metilsulfonilmetano. Antiinflamatório articular.',NULL,'{dog,cat}'),
('Probiótico Bacillus subtilis pó oral','medication','suplemento','un','Suporte microbiota intestinal.',NULL,'{dog,cat}'),
('Prebiótico + Probiótico sachê','medication','suplemento','un','Suporte disbiose e diarreia.',NULL,'{dog,cat}'),
('S-adenosilmetionina (SAMe) 400mg comprimido','medication','suplemento','un','Suporte hepatocelular.',NULL,'{dog,cat}'),
('Silimarina 200mg cápsula','medication','suplemento','un','Hepatoprotetor. Hepatite crônica.',NULL,'{dog,cat}'),
('Ácido ursodesoxicólico 150mg comprimido','medication','suplemento','un','Colerético. Colestase biliar.',NULL,'{dog,cat}'),
('Taurina 250mg cápsula','medication','suplemento','un','Cardioprotegência e suporte retinal felino.',NULL,'{cat}'),
('L-Carnitina 500mg comprimido','medication','suplemento','un','Metabolismo lipídico. Cardiomiopatia dilatada.',NULL,'{dog}'),
('Ácido hialurônico 25mg/ml injetável intra-articular','medication','suplemento','fr','Viscosuplementação articular.',NULL,'{dog,cat}'),
('Probiótico FortiFlora sachê','medication','suplemento','un','Enterococcus faecium. Diarreia.','FortiFlora','{dog,cat}'),

-- ═══════════════════════════════════════════════════════════
-- FLUIDOS E ELETRÓLITOS
-- ═══════════════════════════════════════════════════════════
('Soro fisiológico 0,9% 500ml','clinic_product','fluido','fr','NaCl isotônico. Expansão volêmica.',NULL,'{dog,cat}'),
('Soro fisiológico 0,9% 250ml','clinic_product','fluido','fr','Fluidoterapia em pequenos volumes.',NULL,'{dog,cat}'),
('Soro fisiológico 0,9% 100ml','clinic_product','fluido','fr','Diluição de medicamentos.',NULL,'{dog,cat}'),
('Ringer Lactato 500ml','clinic_product','fluido','fr','Solução polieletrolítica isotônica. Primeira escolha.',NULL,'{dog,cat}'),
('Glicose 5% 500ml','clinic_product','fluido','fr','Solução de manutenção energética.',NULL,'{dog,cat}'),
('Glicose 50% 10ml ampola','clinic_product','fluido','amp','Hipoglicemia grave. Diluir antes de usar.',NULL,'{dog,cat}'),
('Ringer Simples 500ml','clinic_product','fluido','fr','Reposição de eletrólitos.',NULL,'{dog,cat}'),
('Cloreto de potássio 19,1% 10ml injetável','clinic_product','fluido','amp','Hipocalemia. Diluir OBRIGATORIAMENTE.',NULL,'{dog,cat}'),
('Gluconato de cálcio 10% 10ml injetável','clinic_product','fluido','amp','Hipocalcemia. Eclâmpsia.',NULL,'{dog,cat}'),
('Bicarbonato de sódio 8,4% 10ml injetável','clinic_product','fluido','amp','Acidose metabólica. Diluir antes de usar.',NULL,'{dog,cat}'),
('Solução de manutenção pediátrica 500ml','clinic_product','fluido','fr','Filhotes e neonatos.',NULL,'{dog,cat}'),

-- ═══════════════════════════════════════════════════════════
-- INSUMOS DE CLÍNICA
-- ═══════════════════════════════════════════════════════════
('Luva de procedimento não estéril P (cx100)','clinic_product','insumo','cx','Látex ou nitrila. Procedimentos gerais.',NULL,NULL),
('Luva de procedimento não estéril M (cx100)','clinic_product','insumo','cx','Látex ou nitrila.',NULL,NULL),
('Luva de procedimento não estéril G (cx100)','clinic_product','insumo','cx','Látex ou nitrila.',NULL,NULL),
('Luva cirúrgica estéril 7,0 par','clinic_product','insumo','par','Látex estéril. Cirurgias.',NULL,NULL),
('Luva cirúrgica estéril 7,5 par','clinic_product','insumo','par','Látex estéril.',NULL,NULL),
('Luva cirúrgica estéril 8,0 par','clinic_product','insumo','par','Látex estéril.',NULL,NULL),
('Seringa 1ml agulha acoplada','clinic_product','insumo','un','Para medicamentos de pequeno volume.',NULL,NULL),
('Seringa 3ml sem agulha','clinic_product','insumo','un','Uso geral.',NULL,NULL),
('Seringa 5ml sem agulha','clinic_product','insumo','un','Uso geral.',NULL,NULL),
('Seringa 10ml sem agulha','clinic_product','insumo','un','Medicamentos e flush.',NULL,NULL),
('Seringa 20ml sem agulha','clinic_product','insumo','un','Lavagens e fluidoterapia.',NULL,NULL),
('Seringa 60ml sem agulha','clinic_product','insumo','un','Nutrição enteral e lavagem.',NULL,NULL),
('Agulha hipodérmica 13x4,5mm','clinic_product','insumo','cx','Caixa 100un. SC em filhotes.',NULL,NULL),
('Agulha hipodérmica 25x7mm','clinic_product','insumo','cx','SC e IM em gatos.',NULL,NULL),
('Agulha hipodérmica 25x8mm','clinic_product','insumo','cx','SC e IM.',NULL,NULL),
('Agulha hipodérmica 30x7mm','clinic_product','insumo','cx','IM em cães e gatos.',NULL,NULL),
('Agulha hipodérmica 40x12mm','clinic_product','insumo','cx','IM em cães grandes.',NULL,NULL),
('Cateter endovenoso 20G','clinic_product','insumo','un','Acesso venoso adulto.',NULL,NULL),
('Cateter endovenoso 22G','clinic_product','insumo','un','Acesso venoso padrão.',NULL,NULL),
('Cateter endovenoso 24G','clinic_product','insumo','un','Filhotes e gatos.',NULL,NULL),
('Cateter endovenoso 26G','clinic_product','insumo','un','Neonatos.',NULL,NULL),
('Equipo macrogotas','clinic_product','insumo','un','Fluidoterapia padrão.',NULL,NULL),
('Equipo microgotas','clinic_product','insumo','un','Fluidoterapia precisa para gatos.',NULL,NULL),
('Equipo para bomba de infusão','clinic_product','insumo','un','Infusão controlada.',NULL,NULL),
('Gaze estéril 7,5x7,5cm (pct 5un)','clinic_product','insumo','pct','Curativo e compressão.',NULL,NULL),
('Gaze não estéril rolo 91 fios','clinic_product','insumo','rl','Curativo geral.',NULL,NULL),
('Algodão hidrófilo rolo 100g','clinic_product','insumo','rl','Limpeza e curativo.',NULL,NULL),
('Atadura crepe 10cm x 4,5m','clinic_product','insumo','un','Imobilização e curativo.',NULL,NULL),
('Atadura crepe 15cm x 4,5m','clinic_product','insumo','un','Imobilização membros maiores.',NULL,NULL),
('Bandagem elástica coesiva 7,5cm','clinic_product','insumo','un','Penso final de curativo. Não adere à pelagem.','Coban',NULL),
('Bandagem elástica coesiva 10cm','clinic_product','insumo','un','Membros grandes.','Coban',NULL),
('Esparadrapo microporoso 2,5cm','clinic_product','insumo','rl','Fixação de curativos e cateteres.',NULL,NULL),
('Fita microporosa 5cm','clinic_product','insumo','rl','Fixação de curativos.',NULL,NULL),
('Lâmina de bisturi n°15 (cx100)','clinic_product','insumo','cx','Incisões precisas.',NULL,NULL),
('Lâmina de bisturi n°22 (cx100)','clinic_product','insumo','cx','Incisões gerais.',NULL,NULL),
('Fio Mononylon 3-0 agulha 2cm','clinic_product','insumo','un','Sutura de pele. Não absorvível.',NULL,NULL),
('Fio Mononylon 4-0 agulha 1,5cm','clinic_product','insumo','un','Sutura delicada de pele.',NULL,NULL),
('Fio Mononylon 5-0 agulha 1,2cm','clinic_product','insumo','un','Sutura ocular e microcirurgia.',NULL,NULL),
('Fio Vicryl 2-0 agulha 2,5cm','clinic_product','insumo','un','Sutura absorvível de tecido subcutâneo.',NULL,NULL),
('Fio Vicryl 3-0 agulha 2cm','clinic_product','insumo','un','Sutura absorvível plano muscular.',NULL,NULL),
('Fio Catgut Cromado 0','clinic_product','insumo','un','Absorvível natural. Tecidos internos.',NULL,NULL),
('Fio PDS 4-0 agulha 1,5cm','clinic_product','insumo','un','Absorvível sintético longa duração.',NULL,NULL),
('Cânula traqueal 3mm sem balonete','clinic_product','insumo','un','Intubação filhotes e gatos.',NULL,NULL),
('Cânula traqueal 5mm sem balonete','clinic_product','insumo','un','Intubação gatos e cães pequenos.',NULL,NULL),
('Cânula traqueal 7mm com balonete','clinic_product','insumo','un','Intubação cães médios.',NULL,NULL),
('Cânula traqueal 9mm com balonete','clinic_product','insumo','un','Intubação cães grandes.',NULL,NULL),
('Sonda uretral silicone 4 Fr','clinic_product','insumo','un','Gatos machos. Obstrução uretral.',NULL,NULL),
('Sonda uretral silicone 6 Fr','clinic_product','insumo','un','Gatos e cães pequenos.',NULL,NULL),
('Sonda uretral silicone 8 Fr','clinic_product','insumo','un','Cães médios.',NULL,NULL),
('Sonda uretral polipropileno 8 Fr','clinic_product','insumo','un','Cateterismo vesical temporário.',NULL,NULL),
('Sonda nasogástrica 8 Fr','clinic_product','insumo','un','Nutrição enteral e descompressão.',NULL,NULL),
('Frasco coletor de urina 50ml','clinic_product','insumo','un','Urinálise.',NULL,NULL),
('Tubo EDTA 2ml para hemograma','clinic_product','insumo','un','Coleta de sangue para CBC.',NULL,NULL),
('Tubo seco 5ml para bioquímica','clinic_product','insumo','un','Coleta para exames bioquímicos.',NULL,NULL),
('Álcool 70% INPM 500ml','clinic_product','insumo','fr','Antisséptico de superfície.',NULL,NULL),
('Álcool 96° GL 500ml','clinic_product','insumo','fr','Esterilização a frio.',NULL,NULL),
('Álcool gel 70% 500ml','clinic_product','insumo','fr','Antisséptico de mãos.',NULL,NULL),
('Iodo povidona degermante 1L','clinic_product','insumo','fr','Preparação campo cirúrgico.',NULL,NULL),
('Iodo povidona tópico 1L','clinic_product','insumo','fr','Antisséptico de feridas.',NULL,NULL),
('Clorexidina 4% degermante 1L','clinic_product','insumo','fr','Degermação cirúrgica das mãos.',NULL,NULL),
('Clorexidina 0,5% tópico 1L','clinic_product','insumo','fr','Antisséptico tópico geral.',NULL,NULL),
('Glutaraldeído 2% solução 1L','clinic_product','insumo','fr','Esterilização de instrumentais.',NULL,NULL),
('Papel grau cirúrgico rolo 20cm','clinic_product','insumo','rl','Embalagem para autoclave.',NULL,NULL),
('Papel grau cirúrgico rolo 30cm','clinic_product','insumo','rl','Embalagem para autoclave instrumentos maiores.',NULL,NULL),
('Filme radiográfico 18x24cm','clinic_product','insumo','cx','Radiologia analógica.',NULL,NULL),
('Filme radiográfico 24x30cm','clinic_product','insumo','cx','Radiologia analógica.',NULL,NULL),
('Fita adesiva cirúrgica 2,5cm','clinic_product','insumo','rl','Fixação de curativos cirúrgicos.',NULL,NULL),
('Dreno penrose 1/4 pol','clinic_product','insumo','un','Drenagem de feridas e abscessos.',NULL,NULL),
('Dreno penrose 1/2 pol','clinic_product','insumo','un','Drenagem em cavidades.',NULL,NULL),
('Máscara cirúrgica descartável (cx50)','clinic_product','insumo','cx','EPI padrão.',NULL,NULL),
('Gorro cirúrgico descartável (cx100)','clinic_product','insumo','cx','EPI padrão.',NULL,NULL),
('Propé descartável (par)','clinic_product','insumo','par','EPI padrão.',NULL,NULL),
('Avental cirúrgico descartável G','clinic_product','insumo','un','EPI cirúrgico estéril.',NULL,NULL),
('Kit de sutura estéril','clinic_product','insumo','un','Porta-agulha, pinça e tesoura descartáveis.',NULL,NULL),
('Bisturi elétrico caneta descartável','clinic_product','insumo','un','Hemostasia e corte monopolar.',NULL,NULL),
('Fita indicadora autoclave','clinic_product','insumo','rl','Controle de processo de esterilização.',NULL,NULL),
('Integrador biológico geobacillus','clinic_product','insumo','un','Controle biológico de autoclave.',NULL,NULL);
