-- Seed: Produtos de banho e tosa (~350 itens)
INSERT INTO product_catalog_global (name, category, subcategory, unit, description, common_brand, species) VALUES

-- ═══════════════════════════════════════════════════════════
-- SHAMPOOS
-- ═══════════════════════════════════════════════════════════
('Shampoo neutro para cães e gatos 500ml','grooming_supply','shampoo','fr','pH neutro 7. Uso frequente. Sem corantes.',NULL,'{dog,cat}'),
('Shampoo neutro para cães e gatos 1L','grooming_supply','shampoo','fr','Econômico para uso profissional.',NULL,'{dog,cat}'),
('Shampoo neutro para cães e gatos 5L','grooming_supply','shampoo','fr','Galão profissional. Alta diluição 1:10.',NULL,'{dog,cat}'),
('Shampoo antipulgas com piretrina 500ml','grooming_supply','shampoo','fr','Piretrina natural. Banho antipulgas.',NULL,'{dog,cat}'),
('Shampoo antipulgas com citronela 500ml','grooming_supply','shampoo','fr','Repelente natural de pulgas e carrapatos.',NULL,'{dog,cat}'),
('Shampoo antipulgas e carrapatos 500ml','grooming_supply','shampoo','fr','Ação dupla contra ectoparasitas.',NULL,'{dog}'),
('Shampoo medicado clorexidina 4% 250ml','grooming_supply','shampoo','fr','Antisséptico. Piodermite e dermatite bacteriana.',NULL,'{dog,cat}'),
('Shampoo medicado clorexidina 4% 500ml','grooming_supply','shampoo','fr','Uso profissional.',NULL,'{dog,cat}'),
('Shampoo medicado cetoconazol 2% 250ml','grooming_supply','shampoo','fr','Antifúngico. Malassezia e dermatofitose.',NULL,'{dog,cat}'),
('Shampoo medicado cetoconazol 2% 500ml','grooming_supply','shampoo','fr','Uso profissional antifúngico.',NULL,'{dog,cat}'),
('Shampoo clorexidina + cetoconazol 500ml','grooming_supply','shampoo','fr','Dupla ação: antibacteriana + antifúngica.',NULL,'{dog,cat}'),
('Shampoo peróxido de benzoíla 2,5% 250ml','grooming_supply','shampoo','fr','Queratolítico. Seborréia e foliculite.',NULL,'{dog}'),
('Shampoo à base de aveia hidratante 500ml','grooming_supply','shampoo','fr','Calmante. Pele seca e sensível.',NULL,'{dog,cat}'),
('Shampoo à base de aveia hidratante 1L','grooming_supply','shampoo','fr','Profissional. Anti-prurido natural.',NULL,'{dog,cat}'),
('Shampoo de aloe vera hidratante 500ml','grooming_supply','shampoo','fr','Hidratante e calmante para peles irritadas.',NULL,'{dog,cat}'),
('Shampoo de aloe vera + mel 500ml','grooming_supply','shampoo','fr','Hidratação profunda.',NULL,'{dog,cat}'),
('Shampoo de coco hidratante 500ml','grooming_supply','shampoo','fr','Ação hidratante e brilho.',NULL,'{dog,cat}'),
('Shampoo de argan hidratante 500ml','grooming_supply','shampoo','fr','Óleo de argan. Pelagem brilhosa.',NULL,'{dog,cat}'),
('Shampoo clarificante branco 500ml','grooming_supply','shampoo','fr','Para pelos brancos e prateados.',NULL,'{dog,cat}'),
('Shampoo clarificante azul 500ml','grooming_supply','shampoo','fr','Neutraliza amarelado em pelos brancos.',NULL,'{dog,cat}'),
('Shampoo escurecedor para pelos pretos 500ml','grooming_supply','shampoo','fr','Realça tons escuros.',NULL,'{dog,cat}'),
('Shampoo realçador de cor dourada 500ml','grooming_supply','shampoo','fr','Para Golden Retriever e similares.',NULL,'{dog}'),
('Shampoo realçador pelagem ruiva 500ml','grooming_supply','shampoo','fr','Tons avermelhados.',NULL,'{dog,cat}'),
('Shampoo revitalizante de cachos 500ml','grooming_supply','shampoo','fr','Para Poodle, Bichon e raças cacheadas.',NULL,'{dog}'),
('Shampoo desgordurante profissional 500ml','grooming_supply','shampoo','fr','Remove excesso de oleosidade e sebum.',NULL,'{dog,cat}'),
('Shampoo desgordurante 5L','grooming_supply','shampoo','fr','Galão profissional.',NULL,'{dog,cat}'),
('Shampoo antipruriginoso com mentol 500ml','grooming_supply','shampoo','fr','Alívio imediato do prurido.',NULL,'{dog,cat}'),
('Shampoo antipruriginoso com colloidal oatmeal 500ml','grooming_supply','shampoo','fr','Aveia coloidal. Dermatite atópica.',NULL,'{dog,cat}'),
('Shampoo hidratante com proteínas do leite 500ml','grooming_supply','shampoo','fr','Fortalece a haste do pelo.',NULL,'{dog,cat}'),
('Shampoo com queratina 500ml','grooming_supply','shampoo','fr','Reconstrução capilar. Pelo quebradiço.',NULL,'{dog,cat}'),
('Shampoo com queratina profissional 1L','grooming_supply','shampoo','fr','Alta concentração de queratina hidrolisada.',NULL,'{dog,cat}'),
('Shampoo detox carvão ativado 500ml','grooming_supply','shampoo','fr','Purifica pelagem e pele.',NULL,'{dog,cat}'),
('Shampoo dry (a seco) 200ml','grooming_supply','shampoo','fr','Para pets que não toleram banho molhado.',NULL,'{dog,cat}'),
('Shampoo dry profissional 500ml','grooming_supply','shampoo','fr','Banho a seco profissional.',NULL,'{dog,cat}'),
('Shampoo premium raças pequenas 500ml','grooming_supply','shampoo','fr','Formulação delicada para raças toy.',NULL,'{dog}'),
('Shampoo premium raças grandes 500ml','grooming_supply','shampoo','fr','Alta diluição. Cães de grande porte.',NULL,'{dog}'),
('Shampoo para filhotes 300ml','grooming_supply','shampoo','fr','Lágrimas neutras. Seguro para neonatos.',NULL,'{dog,cat}'),
('Shampoo para filhotes 500ml','grooming_supply','shampoo','fr','Fórmula suave. Sem parabenos.',NULL,'{dog,cat}'),
('Shampoo desodorizante 500ml','grooming_supply','shampoo','fr','Neutraliza odores. Longa duração.',NULL,'{dog,cat}'),
('Shampoo desodorizante enzimático 500ml','grooming_supply','shampoo','fr','Enzimas quebram compostos odoríferos.',NULL,'{dog,cat}'),
('Shampoo antisseborreico 500ml','grooming_supply','shampoo','fr','Seborréia seca e oleosa.',NULL,'{dog}'),
('Shampoo antisseborreico com enxofre 500ml','grooming_supply','shampoo','fr','Enxofre + ácido salicílico.',NULL,'{dog}'),
('Shampoo para gatos de pelo longo 500ml','grooming_supply','shampoo','fr','Fácil desembaraço. Pelo longo.',NULL,'{cat}'),
('Shampoo para gatos de pelo curto 500ml','grooming_supply','shampoo','fr','Suave e rápido enxágue.',NULL,'{cat}'),
('Shampoo de baunilha e amêndoas 500ml','grooming_supply','shampoo','fr','Fragrância premium. Pelo suave.',NULL,'{dog,cat}'),
('Shampoo de lavanda relaxante 500ml','grooming_supply','shampoo','fr','Fragrância lavanda. Efeito calmante.',NULL,'{dog,cat}'),
('Shampoo concentrado profissional 5L (diluição 1:20)','grooming_supply','shampoo','fr','Alta diluição. Custo-benefício profissional.',NULL,'{dog,cat}'),
('Shampoo concentrado 500ml (diluição 1:10)','grooming_supply','shampoo','fr','Concentrado para diluição em pet shop.',NULL,'{dog,cat}'),
('Shampoo clareador com camomila 500ml','grooming_supply','shampoo','fr','Camomila clarifica e suaviza pelos claros.',NULL,'{dog,cat}'),
('Shampoo pré-tosa desgordurante 500ml','grooming_supply','shampoo','fr','Remove oleosidade para facilitar a tosa.',NULL,'{dog,cat}'),
('Shampoo pós-tosa cicatrizante 500ml','grooming_supply','shampoo','fr','Acelera recuperação da pele após a tosa.',NULL,'{dog,cat}'),

-- ═══════════════════════════════════════════════════════════
-- CONDICIONADORES E CREMES
-- ═══════════════════════════════════════════════════════════
('Condicionador hidratante 500ml','grooming_supply','condicionador','fr','Hidratação pós-banho. Todos os tipos de pelo.',NULL,'{dog,cat}'),
('Condicionador hidratante 1L','grooming_supply','condicionador','fr','Uso profissional.',NULL,'{dog,cat}'),
('Condicionador de aveia 500ml','grooming_supply','condicionador','fr','Calmante. Pele seca e sensível.',NULL,'{dog,cat}'),
('Condicionador de aloe vera 500ml','grooming_supply','condicionador','fr','Hidratação natural.',NULL,'{dog,cat}'),
('Condicionador com queratina 500ml','grooming_supply','condicionador','fr','Reconstrução e proteção do pelo.',NULL,'{dog,cat}'),
('Condicionador com óleo de argan 500ml','grooming_supply','condicionador','fr','Brilho e maciez intensos.',NULL,'{dog,cat}'),
('Condicionador desembaraçador 500ml','grooming_supply','condicionador','fr','Facilita a escovação. Reduz eletricidade estática.',NULL,'{dog,cat}'),
('Condicionador desembaraçador 1L','grooming_supply','condicionador','fr','Profissional. Para pelos longos e encaracolados.',NULL,'{dog,cat}'),
('Condicionador para filhotes 300ml','grooming_supply','condicionador','fr','Fórmula suave para filhotes.',NULL,'{dog,cat}'),
('Creme de pentear sem enxágue 300ml','grooming_supply','condicionador','fr','Leave-in. Facilita a escovação.',NULL,'{dog,cat}'),
('Creme de pentear com proteínas 300ml','grooming_supply','condicionador','fr','Fortalece e protege o pelo.',NULL,'{dog,cat}'),
('Máscara de hidratação 300g','grooming_supply','condicionador','tb','Hidratação intensa. Uso semanal.',NULL,'{dog,cat}'),
('Máscara reconstrutora de queratina 300g','grooming_supply','condicionador','tb','Reconstrução capilar profunda.',NULL,'{dog,cat}'),
('Leave-in spray desembaraçador 300ml','grooming_supply','condicionador','fr','Spray leave-in. Facilita escovação diária.',NULL,'{dog,cat}'),
('Leave-in protetor térmico spray 200ml','grooming_supply','condicionador','fr','Protege contra o secador.',NULL,'{dog,cat}'),
('Sérum brilhante para pelo 100ml','grooming_supply','condicionador','fr','Finalizador. Brilho e controle de frizz.',NULL,'{dog,cat}'),

-- ═══════════════════════════════════════════════════════════
-- PERFUMES E COLÔNIAS
-- ═══════════════════════════════════════════════════════════
('Colônia pet floral 100ml','grooming_supply','perfume','fr','Fragrância floral delicada.',NULL,'{dog,cat}'),
('Colônia pet lavanda 100ml','grooming_supply','perfume','fr','Fragrância relaxante de lavanda.',NULL,'{dog,cat}'),
('Colônia pet cítrica 100ml','grooming_supply','perfume','fr','Notas cítricas refrescantes.',NULL,'{dog,cat}'),
('Colônia pet baunilha 100ml','grooming_supply','perfume','fr','Fragrância doce e sofisticada.',NULL,'{dog,cat}'),
('Colônia pet talco 100ml','grooming_supply','perfume','fr','Clássico aroma de talco.',NULL,'{dog,cat}'),
('Colônia pet coco 100ml','grooming_supply','perfume','fr','Fragrância tropical de coco.',NULL,'{dog,cat}'),
('Colônia pet baby 100ml','grooming_supply','perfume','fr','Aroma suave estilo bebê.',NULL,'{dog,cat}'),
('Colônia pet masculina 100ml','grooming_supply','perfume','fr','Fragrância amadeirada para machos.',NULL,'{dog,cat}'),
('Colônia pet feminina 100ml','grooming_supply','perfume','fr','Fragrância floral para fêmeas.',NULL,'{dog,cat}'),
('Colônia pet premium 50ml','grooming_supply','perfume','fr','Fragrância de alta qualidade.',NULL,'{dog,cat}'),
('Colônia pet antipulgas citronela 100ml','grooming_supply','perfume','fr','Repelente e perfumado.',NULL,'{dog,cat}'),
('Desodorizante spray corporal pet 200ml','grooming_supply','perfume','fr','Neutraliza odores entre banhos.',NULL,'{dog,cat}'),
('Desodorizante pó absorvente de odores 100g','grooming_supply','perfume','un','Absorve umidade e odores.',NULL,'{dog,cat}'),
('Perfume pós-banho concentrado 15ml','grooming_supply','perfume','fr','Alta fixação.',NULL,'{dog,cat}'),
('Perfume pós-banho splash 250ml','grooming_supply','perfume','fr','Uso generoso após o banho.',NULL,'{dog,cat}'),

-- ═══════════════════════════════════════════════════════════
-- FERRAMENTAS DE TOSA
-- ═══════════════════════════════════════════════════════════
('Máquina de tosa profissional 220V','grooming_supply','ferramenta_tosa','un','Tosa completa. Motor de alta performance.',NULL,'{dog,cat}'),
('Máquina de tosa sem fio recarregável','grooming_supply','ferramenta_tosa','un','Bateria de longa duração. Portátil.',NULL,'{dog,cat}'),
('Lâmina de tosa 3F (13mm)','grooming_supply','ferramenta_tosa','un','Pelo curto e médio.',NULL,'{dog,cat}'),
('Lâmina de tosa 4F (9,5mm)','grooming_supply','ferramenta_tosa','un','Corte médio.',NULL,'{dog,cat}'),
('Lâmina de tosa 7F (3mm)','grooming_supply','ferramenta_tosa','un','Corte curto. Body clip.',NULL,'{dog,cat}'),
('Lâmina de tosa 10 (1,6mm)','grooming_supply','ferramenta_tosa','un','Tosa rente.',NULL,'{dog,cat}'),
('Lâmina de tosa 30 (0,5mm)','grooming_supply','ferramenta_tosa','un','Tosa sanitária e cara.',NULL,'{dog,cat}'),
('Lâmina de tosa 40 (0,25mm)','grooming_supply','ferramenta_tosa','un','Cirúrgica. Skin.',NULL,'{dog,cat}'),
('Pente-guia #1 (3mm)','grooming_supply','ferramenta_tosa','un','Guia para máquina.',NULL,'{dog,cat}'),
('Pente-guia #2 (6mm)','grooming_supply','ferramenta_tosa','un','Guia médio.',NULL,'{dog,cat}'),
('Pente-guia #3 (9mm)','grooming_supply','ferramenta_tosa','un','Guia alto.',NULL,'{dog,cat}'),
('Pente-guia #4 (12mm)','grooming_supply','ferramenta_tosa','un','Guia extra alto.',NULL,'{dog,cat}'),
('Tesoura de corte reta 7 pol','grooming_supply','ferramenta_tosa','un','Aço inox. Corte de modelagem.',NULL,'{dog,cat}'),
('Tesoura de corte reta 8 pol','grooming_supply','ferramenta_tosa','un','Para cães de grande porte.',NULL,'{dog,cat}'),
('Tesoura curva 7 pol','grooming_supply','ferramenta_tosa','un','Modelagem de contornos curvos.',NULL,'{dog,cat}'),
('Tesoura de desbaste 46 dentes','grooming_supply','ferramenta_tosa','un','Desbaste e volume.',NULL,'{dog,cat}'),
('Tesoura de desbaste 30 dentes','grooming_supply','ferramenta_tosa','un','Desbaste suave.',NULL,'{dog,cat}'),
('Tesoura de acabamento ponta arredondada 5 pol','grooming_supply','ferramenta_tosa','un','Segurança para face e patas.',NULL,'{dog,cat}'),
('Escova de cerdas naturais','grooming_supply','ferramenta_tosa','un','Distribuição de óleos naturais. Pelo curto.',NULL,'{dog,cat}'),
('Escova de cerdas mistas','grooming_supply','ferramenta_tosa','un','Versátil. Todos os tipos de pelo.',NULL,'{dog,cat}'),
('Escova de pinos com almofada','grooming_supply','ferramenta_tosa','un','Desembaraço. Pelo médio e longo.',NULL,'{dog,cat}'),
('Escova slicker pequena','grooming_supply','ferramenta_tosa','un','Puas finas. Remove pelos soltos.',NULL,'{dog,cat}'),
('Escova slicker média','grooming_supply','ferramenta_tosa','un','Uso diário. Pelos soltos e nós superficiais.',NULL,'{dog,cat}'),
('Escova slicker grande','grooming_supply','ferramenta_tosa','un','Para cães de médio e grande porte.',NULL,'{dog}'),
('Escova slicker curvo profissional','grooming_supply','ferramenta_tosa','un','Profissional. Múltiplos tipos de pelo.',NULL,'{dog,cat}'),
('Pente de aço inox fino','grooming_supply','ferramenta_tosa','un','Verificação de nós e pulgas.',NULL,'{dog,cat}'),
('Pente de aço inox médio','grooming_supply','ferramenta_tosa','un','Desembaraço geral.',NULL,'{dog,cat}'),
('Pente de aço inox para bigode','grooming_supply','ferramenta_tosa','un','Face e bigode Schnauzer e similares.',NULL,'{dog}'),
('Pente desembaraçador com dentes giratórios','grooming_supply','ferramenta_tosa','un','Nós sem puxar o pelo.',NULL,'{dog,cat}'),
('Rasqueadeira de borracha','grooming_supply','ferramenta_tosa','un','Remove pelos mortos no banho.',NULL,'{dog,cat}'),
('Rasqueadeira metálica','grooming_supply','ferramenta_tosa','un','Remoção de pelo morto.',NULL,'{dog,cat}'),
('Luva de borracha para retirada de pelo','grooming_supply','ferramenta_tosa','un','Massagem + remoção de pelo solto.',NULL,'{dog,cat}'),
('Furminator pelo curto P','grooming_supply','ferramenta_tosa','un','Dessedding. Remove pelo de subpelo.','FURminator','{dog,cat}'),
('Furminator pelo curto M','grooming_supply','ferramenta_tosa','un','Cães médios pelo curto.','FURminator','{dog,cat}'),
('Furminator pelo longo P','grooming_supply','ferramenta_tosa','un','Pelo longo e dupla camada.','FURminator','{dog,cat}'),
('Furminator pelo longo G','grooming_supply','ferramenta_tosa','un','Cães grandes pelo longo.','FURminator','{dog}'),
('Cortador de unhas guilhotina P','grooming_supply','ferramenta_tosa','un','Gatos e cães pequenos.',NULL,'{dog,cat}'),
('Cortador de unhas guilhotina M','grooming_supply','ferramenta_tosa','un','Cães médios.',NULL,'{dog}'),
('Cortador de unhas guilhotina G','grooming_supply','ferramenta_tosa','un','Cães grandes.',NULL,'{dog}'),
('Cortador de unhas tipo tesoura','grooming_supply','ferramenta_tosa','un','Controle preciso para gatos.',NULL,'{cat}'),
('Lima de unhas para pets','grooming_supply','ferramenta_tosa','un','Acabamento pós-corte de unhas.',NULL,'{dog,cat}'),
('Dremel pet para lixamento de unhas','grooming_supply','ferramenta_tosa','un','Elétrico. Lixamento progressivo.',NULL,'{dog,cat}'),
('Pinça para pelos de ouvido','grooming_supply','ferramenta_tosa','un','Remoção de pelos do canal auricular.',NULL,'{dog}'),
('Spray lubrificante para lâminas','grooming_supply','ferramenta_tosa','fr','Resfria, lubrifica e limpa lâminas.',NULL,NULL),
('Spray refrigerante para lâminas','grooming_supply','ferramenta_tosa','fr','Resfria lâminas aquecidas.',NULL,NULL),
('Óleo lubrificante para máquina de tosa 100ml','grooming_supply','ferramenta_tosa','fr','Lubrificação de engrenagens.',NULL,NULL),
('Estojo profissional para tesouras','grooming_supply','ferramenta_tosa','un','Armazenamento e proteção.',NULL,NULL),

-- ═══════════════════════════════════════════════════════════
-- SECAGEM E BANHO
-- ═══════════════════════════════════════════════════════════
('Secador profissional de alta potência 2000W','grooming_supply','secagem','un','Alta temperatura. Secagem rápida.',NULL,NULL),
('Secador tipo canhão profissional','grooming_supply','secagem','un','Alta velocidade de ar. Peludos.',NULL,NULL),
('Toalha de microfibra pet P','grooming_supply','secagem','un','Secagem rápida.',NULL,'{dog,cat}'),
('Toalha de microfibra pet M','grooming_supply','secagem','un','Cães médios.',NULL,'{dog}'),
('Toalha de microfibra pet G','grooming_supply','secagem','un','Cães grandes.',NULL,'{dog}'),
('Toalha de microfibra pet GG','grooming_supply','secagem','un','Cães gigantes.',NULL,'{dog}'),
('Toalha de algodão para pet M','grooming_supply','secagem','un','Absorção tradicional.',NULL,'{dog,cat}'),
('Toalha de algodão para pet G','grooming_supply','secagem','un','Cães grandes.',NULL,'{dog}'),
('Roupão de secagem P','grooming_supply','secagem','un','Absorvente. Pós-banho.',NULL,'{dog,cat}'),
('Roupão de secagem M','grooming_supply','secagem','un','Cães médios.',NULL,'{dog}'),
('Roupão de secagem G','grooming_supply','secagem','un','Cães grandes.',NULL,'{dog}'),
('Luva de banho de silicone','grooming_supply','banho','un','Massagem e remoção de pelos no banho.',NULL,'{dog,cat}'),
('Esponja de banho profissional','grooming_supply','banho','un','Distribuição uniforme do shampoo.',NULL,'{dog,cat}'),
('Balde dosador de shampoo 10L','grooming_supply','banho','un','Diluição precisa do shampoo.',NULL,NULL),
('Mesa de tosa inox regulável','grooming_supply','banho','un','Mesa profissional com braço de contenção.',NULL,NULL),
('Braço de contenção ajustável','grooming_supply','banho','un','Segurança no banho e tosa.',NULL,NULL),
('Banheira de inox para cães P','grooming_supply','banho','un','Cães até 15kg.',NULL,NULL),
('Banheira de inox para cães G','grooming_supply','banho','un','Cães até 40kg.',NULL,NULL),
('Showerhead com filtro para pet','grooming_supply','banho','un','Pressão regulável. Filtra resíduos.',NULL,NULL),
('Tapete antiderrapante para banheira','grooming_supply','banho','un','Segurança durante o banho.',NULL,NULL),

-- ═══════════════════════════════════════════════════════════
-- CUIDADOS COM OUVIDOS, OLHOS E HIGIENE
-- ═══════════════════════════════════════════════════════════
('Limpador auricular enzimático 100ml','grooming_supply','higiene','fr','Remove cera e detritos do ouvido.',NULL,'{dog,cat}'),
('Limpador auricular 120ml','grooming_supply','higiene','fr','Limpeza semanal do canal auricular.',NULL,'{dog,cat}'),
('Limpador de olhos lacrimal 100ml','grooming_supply','higiene','fr','Remove manchas de lágrima.',NULL,'{dog,cat}'),
('Removedor de manchas de lágrima 60ml','grooming_supply','higiene','fr','Clarea manchas periorbitais.',NULL,'{dog,cat}'),
('Lenço umedecido higiene pet (cx100)','grooming_supply','higiene','cx','Limpeza entre banhos.',NULL,'{dog,cat}'),
('Lenço umedecido para olhos (cx30)','grooming_supply','higiene','cx','Limpeza delicada da região ocular.',NULL,'{dog,cat}'),
('Lenço umedecido para ouvidos (cx30)','grooming_supply','higiene','cx','Limpeza suave do pavilhão auricular.',NULL,'{dog,cat}'),
('Escova dental para pets dupla face','grooming_supply','higiene','un','Escovação dental. Tamanho P e G.',NULL,'{dog,cat}'),
('Dentifrício pet sabor frango 60g','grooming_supply','higiene','un','Pasta dental. Sem flúor.',NULL,'{dog,cat}'),
('Dentifrício pet sabor carne 60g','grooming_supply','higiene','un','Palatável para cães.',NULL,'{dog}'),
('Borracha de limpeza dental','grooming_supply','higiene','un','Limpeza mecânica dos dentes.',NULL,'{dog,cat}'),
('Spray bucal refrescante 60ml','grooming_supply','higiene','fr','Halitose. Usar direto na boca.',NULL,'{dog,cat}'),
('Pó absorvente para unhas 30g','grooming_supply','higiene','un','Estanca sangramento no corte de unhas.',NULL,'{dog,cat}'),
('Pomada repelente para tosa 100g','grooming_supply','higiene','tb','Previne insetos durante e após a tosa.',NULL,'{dog,cat}'),
('Gel calmante pós-tosa 100ml','grooming_supply','higiene','fr','Aloe vera + camomila. Acalma pele irritada.',NULL,'{dog,cat}'),
('Talco higiênico para pets 100g','grooming_supply','higiene','un','Absorve umidade. Genital e dobras.',NULL,'{dog,cat}'),
('Creme para coxins 50g','grooming_supply','higiene','tb','Hidrata e protege almofadinhas.',NULL,'{dog,cat}'),
('Creme para focinho 30g','grooming_supply','higiene','tb','Trata ressecamento do focinho.',NULL,'{dog,cat}'),
('Protetor solar para pets FPS30 50ml','grooming_supply','higiene','fr','Áreas sem pelos. Focinho e orelhas.',NULL,'{dog,cat}'),
('Removedor de nós spray 200ml','grooming_supply','higiene','fr','Facilita a remoção de nós sem cortar.',NULL,'{dog,cat}'),
('Glicerina líquida 100ml','grooming_supply','higiene','fr','Hidratante natural de pelo.',NULL,'{dog,cat}'),
('Pó para expressar glândulas anais','grooming_supply','higiene','un','Facilita expressão manual.',NULL,'{dog,cat}'),

-- ═══════════════════════════════════════════════════════════
-- ACABAMENTO E FINALIZADORES
-- ═══════════════════════════════════════════════════════════
('Spray finalizador brilhante 200ml','grooming_supply','finalizador','fr','Brilho e maciez ao pelo.',NULL,'{dog,cat}'),
('Spray finalizador antiestático 200ml','grooming_supply','finalizador','fr','Elimina eletricidade estática.',NULL,'{dog,cat}'),
('Creme texturizador para topknot 50g','grooming_supply','finalizador','tb','Fixação de penteados. Poodle e Bichon.',NULL,'{dog}'),
('Gel fixador para penteados pet 100g','grooming_supply','finalizador','tb','Topknot e penteados de show.',NULL,'{dog}'),
('Spray de brilho para show 200ml','grooming_supply','finalizador','fr','Alta concentração. Exposições.',NULL,'{dog,cat}'),
('Purpurina vegetal para pets (cores variadas)','grooming_supply','finalizador','un','Decoração para festas. Não tóxica.',NULL,'{dog,cat}'),
('Laço de fita estampado para pets (pct10)','grooming_supply','finalizador','pct','Acabamento de tosa. Decorativo.',NULL,'{dog,cat}'),
('Laço de elástico colorido para pets (pct20)','grooming_supply','finalizador','pct','Laços em borracha colorida.',NULL,'{dog,cat}'),
('Bandana estampada para cães P','grooming_supply','finalizador','un','Acabamento de tosa. Lavável.',NULL,'{dog}'),
('Bandana estampada para cães M','grooming_supply','finalizador','un','Lavável. Estampas variadas.',NULL,'{dog}'),
('Bandana estampada para cães G','grooming_supply','finalizador','un','Cães grandes.',NULL,'{dog}'),
('Gravata borboleta pet P','grooming_supply','finalizador','un','Elegante. Velcro ajustável.',NULL,'{dog,cat}'),
('Gravata borboleta pet M','grooming_supply','finalizador','un','Cães médios.',NULL,'{dog}'),
('Tinta temporária pet safe azul 60ml','grooming_supply','finalizador','fr','Coloração temporária. Não tóxica.',NULL,'{dog}'),
('Tinta temporária pet safe rosa 60ml','grooming_supply','finalizador','fr','Coloração temporária. Não tóxica.',NULL,'{dog}'),
('Tinta temporária pet safe preta 60ml','grooming_supply','finalizador','fr','Coloração temporária.',NULL,'{dog}'),
('Tinta temporária pet safe kit 6 cores','grooming_supply','finalizador','kt','6 cores para estética criativa.',NULL,'{dog}'),
('Lápis dermatográfico pet (chalk)','grooming_supply','finalizador','un','Marcação temporária de pelo.',NULL,'{dog}'),
('Esmalte para unhas de pets 7ml','grooming_supply','finalizador','fr','Base aquosa. Não tóxica.',NULL,'{dog,cat}'),
('Kit nail art para pets','grooming_supply','finalizador','kt','Esmalte + adesivos + top coat.',NULL,'{dog,cat}'),
('Strass e adesivos decorativos para pelo','grooming_supply','finalizador','kt','Decoração de show e festas.',NULL,'{dog,cat}');
